ros__parameters:
  bridges:

    ########### THRUSTER COMMANDS (ROS → GZ) ###########

    - topic_name: "/model/bluerov2/joint/thruster1_joint/cmd_thrust"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster1_joint/ang_vel"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster1_joint/enable_deadband"
      ros_type_name: "std_msgs/msg/Bool"
      gz_type_name: "ignition.msgs.Boolean"
      direction: "ROS_TO_GZ"


    - topic_name: "/model/bluerov2/joint/thruster2_joint/cmd_thrust"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster2_joint/ang_vel"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster2_joint/enable_deadband"
      ros_type_name: "std_msgs/msg/Bool"
      gz_type_name: "ignition.msgs.Boolean"
      direction: "ROS_TO_GZ"


    - topic_name: "/model/bluerov2/joint/thruster3_joint/cmd_thrust"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster3_joint/ang_vel"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster3_joint/enable_deadband"
      ros_type_name: "std_msgs/msg/Bool"
      gz_type_name: "ignition.msgs.Boolean"
      direction: "ROS_TO_GZ"


    - topic_name: "/model/bluerov2/joint/thruster4_joint/cmd_thrust"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster4_joint/ang_vel"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster4_joint/enable_deadband"
      ros_type_name: "std_msgs/msg/Bool"
      gz_type_name: "ignition.msgs.Boolean"
      direction: "ROS_TO_GZ"


    - topic_name: "/model/bluerov2/joint/thruster5_joint/cmd_thrust"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster5_joint/ang_vel"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster5_joint/enable_deadband"
      ros_type_name: "std_msgs/msg/Bool"
      gz_type_name: "ignition.msgs.Boolean"
      direction: "ROS_TO_GZ"


    - topic_name: "/model/bluerov2/joint/thruster6_joint/cmd_thrust"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster6_joint/ang_vel"
      ros_type_name: "std_msgs/msg/Float64"
      gz_type_name: "ignition.msgs.Double"
      direction: "ROS_TO_GZ"

    - topic_name: "/model/bluerov2/joint/thruster6_joint/enable_deadband"
      ros_type_name: "std_msgs/msg/Bool"
      gz_type_name: "ignition.msgs.Boolean"
      direction: "ROS_TO_GZ"


    ########### STATE & SENSORS (GZ → ROS) ###########

    - topic_name: "/model/bluerov2/odometry"
      ros_type_name: "nav_msgs/msg/Odometry"
      gz_type_name: "ignition.msgs.Odometry"
      direction: "GZ_TO_ROS"

    - topic_name: "/model/bluerov2/odometry_with_covariance"
      ros_type_name: "nav_msgs/msg/Odometry"
      gz_type_name: "ignition.msgs.OdometryWithCovariance"
      direction: "GZ_TO_ROS"

    - topic_name: "/model/bluerov2/pose"
      ros_type_name: "geometry_msgs/msg/PoseArray"
      gz_type_name: "ignition.msgs.Pose_V"
      direction: "GZ_TO_ROS"

    - topic_name: "/model/bluerov2/imu"
      ros_type_name: "sensor_msgs/msg/Imu"
      gz_type_name: "ignition.msgs.IMU"
      direction: "GZ_TO_ROS"

    - topic_name: "/world/pool_world/clock"
      topic_name: "/world/pool_world/clock"
      ros_type_name: "rosgraph_msgs/msgs/Clock"
      gz_type_name: "igitoin.msgs.Clock"
      direction: "GZ_TO_ROS"

    # - topic_name: "/model/bluerov2/magnetometer"
    #   ros_type_name: "sensor_msgs/msg/MagneticField"
    #   gz_type_name: "ignition.msgs.Magnetometer"
    #   direction: "GZ_TO_ROS"


    ########### CAMERA (optional) ###########

    # - topic_name: "/model/bluerov2/camera/image"
    #   ros_type_name: "sensor_msgs/msg/Image"
    #   gz_type_name: "ignition.msgs.Image"
    #   direction: "GZ_TO_ROS"

    # - topic_name: "/model/bluerov2/camera/camera_info"
    #   ros_type_name: "sensor_msgs/msg/CameraInfo"
    #   gz_type_name: "ignition.msgs.CameraInfo"
    #   direction: "GZ_TO_ROS"
